version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile.python
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=test
    networks:
      backend:
        ipv4_address: 172.20.0.5
  
  db:
    image: mysql:8
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    ports:
      - 3306:3306
    networks:
      backend:
        ipv4_address: 172.20.0.10
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_password

  reverse-proxy:
    image: haproxy
    restart: always
    networks:
        backend: {}
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw 

  ingress-proxy:
    image: nginx:latest
    restart: always
    network_mode: host
    volumes:
    - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
    - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:rw

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24


secrets:
  mysql_root_password:
    file: .env_mysql_root_password
  mysql_database:
    file: .env_mysql_database
  mysql_user:
    file: .env_mysql_user
  mysql_password:
    file: .env_mysql_password
